int _isupper(int c);
int _isdigit(int c);
int mul(int a, int b);
void print_numbers(void);
void _putchar(char);
void print_most_numbers(void);
void _putchar(char);
void more_numbers(void);
void _putchar(char);
void print_line(int n);
void _putchar(char);
void print_diagonal(int n);
void _putchar(char);
void print_square(int size);
void _putchar(char);
void print_triangle(int size);
void _putchar(char);
